spring.application.name=HandkerSkinsProject

spring.datasource.url=jdbc:postgresql://localhost:5432/handlerskins_db
spring.datasource.username=postgres

# ?????? ?? ????????? ??
spring.datasource.password= ${DB_PASSWORD} 
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ???????? ??? ??????????? ????? ??? ? id ???? ???? ????? ????????? ?????
telegram.bot.token= ${TELEGRAM_BOT_TOKEN}
telegram.bot.username=AnomalyNotificationSkins
telegram.bot.chat-id= ${TELEGRAM_CHAT_ID}

spring.jpa.open-in-view=false

# csgo market
market-csgo.api.base-url=https://market.csgo.com/api/v2
market-csgo.api.key=${MARKET_API_KEY}

# websocket
market-csgo.ws.url=wss://wsprice.csgo.com/connection/websocket
market-csgo.buy.dry-run=true

logging.file.name=logs/handkerskins.log